main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: rhn_support_mbaldess+industrialedge
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mbaldessari
    username: mbaldessari
    email: michele@acksyn.org
    dev_revision: main

  s3:
    bucket:
      name: bandini-s3
      region: us-east-2
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
