storageSystem:
  deploy: true
  inventory:
    useSpecificNodes: false

clusterGroup:
  name: datacenter
  isHubCluster: true

  namespaces:
  - golang-external-secrets
  - open-cluster-management
  - manuela-ml-workspace
  - manuela-tst-all
  - manuela-ci
  - manuela-data-lake
  - staging
  - vault
  - openshift-pipelines
  - openshift-storage
  - redhat-ods-operator:
      operatorGroup: true
      targetNamespaces:
  - edge-workspace
  - edge-test-all
  - edge-ci
  - ml-development:
      labels:
        app.kubernetes.io/instance: edge-anomaly-detection-hub
        kubernetes.io/metadata.name: ml-development
        argocd.argoproj.io/managed-by: edge-anomaly-detection-hub
        modelmesh-enabled: 'true'
        opendatahub.io/dashboard: 'true'
  - redhat-ods-applications:
      labels:
        app.kubernetes.io/instance: edge-anomaly-detection-hub
        kubernetes.io/metadata.name: redhat-ods-applications
        argocd.argoproj.io/managed-by: edge-anomaly-detection-hub
    #  operatorgroupExcludes:
    #  - manuela-ml-workspace

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management

    amqbroker-prod:
      name: amq-broker-rhel8
      namespace: manuela-tst-all

    amqstreams-prod-dev:
      name: amq-streams
      namespaces:
      - manuela-data-lake
      - manuela-tst-all

    camelk-prod-dev:
      name: camel-k
      namespaces:
      - manuela-data-lake
      - manuela-tst-all
      channel: stable-v2
      source: community-operators
      sourceNamespace: openshift-marketplace

    pipelines:
      name: openshift-pipelines-operator-rh
      source: redhat-operators

    odf:
      name: odf-operator
      namespace: openshift-storage
      source: redhat-operators

    ods:
      name: rhods-operator
      channel: alpha
      namespace: redhat-ods-operator

  projects:
  - datacenter
  - production-datalake
  - golang-external-secrets
  - data-science-proj
  - vault

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: datacenter
      chart: acm
      chartVersion: 0.1.*
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
        - /spec/loggingCA

          #odh:
          #name: odh
          #namespace: manuela-ml-workspace
          #project: datacenter
          #path: charts/datacenter/opendatahub

    pipelines:
      name: pipelines
      namespace: manuela-ci
      project: datacenter
      path: charts/datacenter/pipelines

    production-data-lake:
      name: production-data-lake
      namespace: manuela-data-lake
      project: production-datalake
      path: charts/datacenter/manuela-data-lake
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: route.openshift.io
        kind: Route
        jsonPointers:
        - /status
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image

    storage:
      name: storage
      namespace: openshift-storage
      project: datacenter
      chart: openshift-data-foundations
      chartVersion: 0.1.*

    data-science-cluster:
      name: data-science-cluster
      namespace: redhat-ods-applications
      project: data-science-proj
      path: charts/datacenter/data-science-cluster
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: route.openshift.io
        kind: Route
        jsonPointers:
        - /status
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image

    data-science-project:
      name: data-science-project
      namespace: ml-development
      project: data-science-proj
      path: charts/datacenter/data-science-project
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: route.openshift.io
        kind: Route
        jsonPointers:
        - /status
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image

    test:
      name: manuela-test
      namespace: manuela-tst-all
      project: datacenter
      path: charts/datacenter/manuela-tst
      extraValueFiles:
        - /overrides/values-test-imagedata.yaml

    vault:
      name: vault
      namespace: vault
      project: datacenter
      chart: hashicorp-vault
      chartVersion: 0.1.*

    secrets-operator:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: golang-external-secrets
      chart: golang-external-secrets
      chartVersion: 0.1.*

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

  managedClusterGroups:
    factory:
      name: factory
      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
      # targetRevision: main
      helmOverrides:
      # Values must be strings!
      - name: clusterGroup.isHubCluster
        value: "false"
      clusterSelector:
        matchLabels:
          clusterGroup: factory
        matchExpressions:
        - key: vendor
          operator: In
          values:
            - OpenShift

