main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: rhn_support_mbaldess
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mbaldessari
    #username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  s3:
    bucket:
      name: manuela-data-lake
      region: us-west-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint: 
          #url: https://my.custom.endpoint
          enabled: false
