clusterGroup:
  name: factory
  isHubCluster: false

  namespaces:
  - factory-line-dashboard
  - factory-machine-sensor
  - factory-messaging

  subscriptions:
  - name: amq-streams
    namespace: factory-messaging

  - name: amq-broker-rhel8
    namespace: factory-messaging

  - name: camel-k
    namespace: factory-messaging
    channel: stable-v2
    source: community-operators

  projects:
  - factory

  applications:
  - name: stormshift
    project: factory
    path: charts/factory/manuela-factory
    extraValueFiles:
      - /overrides/values-prod-imagedata.yaml

#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main
