main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: rhn_support_mbaldess
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mbaldessari
    username: mbaldessari
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  s3:
    bucket:
      name: bandini-industrial-edge
      region: us-east-2
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
