apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: manuela-kafka-cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true 
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      
      - name: plain (9)
        port: 9092 (10)
        type: internal (11)
        tls: false (12)
        configuration:
          useServiceDnsDomain: true (13)
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication: (14)
          type: tls
    config:
      log.message.format.version: '2.6'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral  
  entityOperator:
    topicOperator: {}
    userOperator: {}
