global:
  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

  s3:
    bucket:
      name: BUCKETNAME
      region: AWSREGION
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false

kafka:
  broker:
    uri: "prod-kafka-cluster-kafka-bootstrap.manuela-data-lake.svc:9092"
    topic:
      temperature: "manuela-factory.iot-sensor-sw-temperature"
      vibration: "manuela-factory.iot-sensor-sw-vibration"

