{{- if .Values.clusterGroup.isHubCluster }}
{{- if .Values.global.originURL }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-anomaly-external-secret
  namespace: manuela-tst-all
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: s3-anomaly
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: "pushsecrets/s3-anomaly"
{{- end }}
{{- end }}

