---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: kafka-hub-user
  namespace: manuela-factory
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: kafka-hub-user
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: "pushsecrets/kafka-user"

