- name: Secret injection of validated-patterns
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    values_secret: "{{ lookup('env', 'HOME') }}/values-secret.yaml"
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
    vault_ns: "vault"
    vault_pod: "vault-0"
    vault_path: "secret/hub"
    debug: False
  
  tasks:
  - name: Run push secrets task
    include_role:
      name: vault_utils
      tasks_from: push_secrets

