---
- name: Vault initialization
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    external_secrets_ns: golang-external-secrets
    external_secrets_sa: golang-external-secrets
  tasks:
  - name: Run vault init tasks
    include_role:
      name: vault_utils
      tasks_from: vault_init
  - name: Unseal vault
    include_role:
      name: vault_utils
      tasks_from: vault_unseal
  - name: Vault secrets init
    include_role:
      name: vault_utils
      tasks_from: vault_secrets_init
