---
- name: Check that KUBECONFIG is correctly set
  ansible.builtin.fail:
    msg: "KUBECONFIG is not set. Please set it so we can inject the secrets into the cluster's vault"
  failed_when: kubeconfig is not defined or kubeconfig | length == 0

# FIXME to use proper k8 ansible collection
- name: Delete vault pod
  ansible.builtin.shell: |
    oc -n vault delete pod vault-0
  register: delete_pod
  async: 7200
  poll: 0

- name: Delete vault pvc
  ansible.builtin.shell: |
    oc -n vault delete pvc data-vault-0
  register: delete_pvc
  async: 7200
  poll: 0

- name: Wait for tasks
  wait_for:
    timeout: 10
