{{- range .Values.s3secret.namespaces }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: {{ . }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: s3-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        "application.properties": "{{ `{{ .s3Secret | b64dec | toString }}` }}"
        "s3Secret": "{{ `{{ .s3Secret | b64dec | toString }}` }}"
  data:
    - secretKey: "s3Secret"
      remoteRef:
        key: {{ $.Values.s3secret.key }}
        property: s3Secret
{{- end }}
